import os
from dotenv import load_dotenv
from groq import Groq  # Import Groq's SDK

load_dotenv()
groq_api_key = os.getenv("GROQ_API_KEY")
client = Groq(
    api_key= groq_api_key 
)

def generate_and_save_story(prompt, file_path):
    try:
        response = client.chat.completions.create(
            model="mixtral-8x7b-32768",  
            messages=[{"role": "user", "content": prompt}],
            temperature=1.0 #changed the temp from 0.7 to 1.0
        )

        story_content = response.choices[0].message.content

        with open(file_path, "w", encoding="utf-8") as file:
            file.write(story_content)
            
        print(f"Story successfully saved to {file_path}")
        return story_content

    except Exception as e:
        print(f"Error: {str(e)}")

text_input = """ A simple definition of a natural disaster is an adverse event initiated by natural processes, such as a sudden change in the earth’s crust or climate. There are plenty of categories that we can use to distinguish natural disasters, but here are the fundamental three:

Geological disasters
Hydrological disasters
Meteorological disaster
These basic categorisations, however, have been blurred in recent years with the growing threat of climate change. Natural disasters that scientists predict may not have happened either with as much frequency, or intensity has been caused by the warmer climate, the rising sea levels, and the breakdown of ecosystems. In this way, the definition of what is a natural disaster and a man-made disaster in Geography is less clear than it has been previously.

Geologicalnatural disasters for kids
Avalanches and Landslides - This is when material runs down a slope of some kind. In the case of an avalanche, this will be snow that has either built up in a vulnerable position or fallen because of a sudden warm climate that has weakened the structure of the ice underneath. It is the same principle for landslides, which tend to occur because of weakened material on mountainsides. This can be because of rain, or excavation. Mines also tend to experience landslides because of the removal of supporting material when harvesting metal or other minerals.



Earthquakes - When the earth’s crust moves, and two plates either converge or shift over one another, a huge amount of energy is released. An earthquake is a result of that energy transferring into seismic waves, which move everything around it. Depending on where the epicentre (the point directly above the collision) is, often determines the consequences. Earthquakes, themselves, are typically not the reason for the damage, but secondary events such as tsunamis, building collapses, and volcanic eruptions are hugely disastrous.



Volcanic eruptions - As mentioned, volcanic eruptions are also a result of the energy that is generated by the movement of tectonic plates. When the earth’s crust generates this energy, some of this travels in the form of heat. Under the earth's surface, it becomes hot enough for the rock to melt and become magma. This molten rock is lighter than the surrounding rock, so starts travelling to the surface, where it eventually explodes out in the form of a volcano. The molten lava, however, is often not the primary concern. The extremely hot gases and clumps of rock that take flight create a deadly pyroclastic flow. The speed with which this travels is typically how the disastrous effects are caused.

Hydrologicalnatural disasters for kids
Floods - Floods can be caused for a number of reasons, and are not always disasters, therefore making the definition of this natural disaster hard to establish in Geography. Floods are an influx of water in an area that is typically dry and is inhabited by humans, such as a city, town or village. This may be caused by unprecedented levels of rain that either flood valleys, or burst boundaries where water is ordinarily contained. It can also be caused by the sudden melting of glaciers, where water travels from high latitudes to lower ground. Sometimes floods are welcomed, especially in natural or rural landscapes, because they can enrich the soil. Check out this page on floodplains for more information about how floods in certain areas of the world are not disasters at all.



Tsunamis - This kind of natural disaster is the earthquake’s seismic waves having a repercussion on the water. Tsunamis are often far more devastating than earthquakes, in that the waves can travel as far as 16 km on land after reaching the coast. And tsunamis do not consist solely of one wave, they usually possess a wave train where four or five waves may arrive after the initial wave hits. There can be up to 100 miles between a seismic wave, meaning the subsequent waves can arrive anywhere between five minutes and two hours later. Check out our tsunami wiki for more information.

Limnic eruptions - These are far less common than the other hydrological natural disasters, as only two events of this kind have been observed. Limnic eruptions or a lake overturn as it is sometimes called, are when pockets of carbon dioxide that have long been sequestered under a body of water, then erupt, travel to the surface, and asphyxiate the humans, animals, and wildlife nearby.

Meteorologicalnatural disasters for kids
Cyclones and hurricanes - These names are used interchangeably, depending on which sea or ocean the event is taking place. Fundamentally, a hurricane occurs when warm moist air begins to rise over the water. When this process continues, large swathes of heavy clouds, a storm, start to swirl. This is because of the earth’s Coriolis Effect, which dictates that anything suspended or in motion over long distances starts to detour from a straight line. When a cyclone reaches land it can be dangerous because it inflicts extreme winds, rainfall, and flooding that can have detrimental effects on the area.



Heatwaves and droughts - These are significant periods of excessively hot weather, which can cause a number of issues, such as deaths from overheating, crop failure, and wildfires. In hot areas of woodland, trees are often dried up by the sun, making them easily flammable and capable of spreading fire to neighbouring trees and buildings.



Blizzards and hail storms - This is when high winds stir up snow that has already fallen, obstructing travel, medical care, and agriculture. Sometimes precipitation, rain, will freeze while in very cold conditions and remains frozen after hitting the ground."""

'''prompt = f"""Generate a comic book narrative based on the provided educational text. The narrative should be engaging, dramatic, and suitable for kids aged 6-10 years.

Guidelines:
Characters: Use famous superheroes as educators and Dr. Octopus as the antagonist.
Story Structure:
First 25-40%: An exciting action sequence where Dr. Octopus causes chaos.
Last 60-75%: Superheroes step in and teach the educational concept.
Tone & Style: Fun, action-packed, and kid-friendly.
Static Scenes: Ensure each moment is static, making it easy to illustrate.
Dialogues: Only one line of dialogue per character per panel.
Narrator Use: The narrator will provide an educational explanation at the end of each page."""'''

alternate_prompt = f"""
Write a comic story on the above text input provided.
Make the scenes static so that it is easy to draw the comic. 
The first few panels will have the buildup to the story and will be unrelated to the educative part.Include Dr octopus as the antagonist.The remaining panels will have the educative part. 
This comic is supposed to be for kids of the age 6-10 years. Try making the story dramatic and engaging for kids.
Use famous superheros as the educators. Don't use elements in the text as the characters.
Spilt the panel as scene: which describes exactly what the character is doing and the character dialogues. Use a narrator wherever required. 
Try to make the educative part include 60-75% of the content of the text provided.
Do not give multiple dialogues in the same panel. Make sure the narrator and the dialogue together add up to around 20 words only. Not more. I will be bankrupt if you do so.
Make sure the story has a happy ending.
{text_input}"""

response = client.chat.completions.create(
            model="mixtral-8x7b-32768",  
            messages=[{"role": "user", "content": alternate_prompt}],
            temperature=1.0 #changed the temp from 0.7 to 1.0
        )

story_content = response.choices[0].message.content

prompt_2=f'''Take the narrative generated from the story and format it into structured JSON for a comic book layout.

JSON Structure Guidelines:
Each page has exactly 4 panels.
Each panel should have:
"scene": A static description of the moment.
"dialogue": Character dialogues (one line per character).
"narrator" : The narrator should be explaining the concept in a fun way relating it with the story. Don't use him unnecessarily.
Don't add messages to me. Just give the plain json structure output. I dont want anything above and below it.
Here is the text generated from the previous prompt: {story_content}'''

response = client.chat.completions.create(
            model="llama-3.2-3b-preview",  
            messages=[{"role": "user", "content": prompt_2}],
            temperature=0 #changed the temp from 0.7 to 1.0
        )

print(response.choices[0].message.content)